source "https://rubygems.org"

gem "lita"
gem "lita-slack"
gem "ejson"
gem "json"

gem "lita-cuslacking", :path => "lita-cuslacking"
gem "byebug"
gem "httparty"

# Uncomment to use the HipChat adapter
# gem "lita-hipchat"

# Uncomment to use the IRC adapter
# gem "lita-irc"

# Add handlers to give Lita new functionality.
# For example:
# gem "lita-google-images"
# gem "lita-karma"
